using System;

class Program
{
    static void Main(string[] args)
    {
        Random randomGenerator = new Random();

        int magicNumber = randomGenerator.Next(1,100);
        int userGuess;
        Console.WriteLine("You are going to guess a random number between 1-100 generated by the computer!");
        int counter = 0;

        do {
            Console.WriteLine("What is your guess?");
            counter++;
            
            userGuess = int.Parse(Console.ReadLine());
            if (userGuess > magicNumber) {
                Console.WriteLine("Lower");
            }
            else if (userGuess < magicNumber) {
                Console.WriteLine("Higher");
            }
            else {
                Console.WriteLine("That's Correct!");
                Console.WriteLine("It took you " + counter + " guesses!");
            }
        }
        while (userGuess != magicNumber);




    }
}